version: "3.8"
services:
  accounts:
    build: ./accounts
    image: tusharsaste/accounts:s4
    ports:
      - "8080:8080"
    networks:
      - tusharsastebank

  loans:
    build: ./loans
    image: tusharsaste/loans:s4
    ports:
      - "8090:8090"
    networks:
      - tusharsastebank

  cards:
    build: ./cards
    image: tusharsaste/cards:s4
    ports:
      - "9000:9000"
    networks:
      - tusharsastebank
networks:
  tusharsastebank:
    driver: "bridge"